{ created_at: 'Sat Apr 02 14:09:41 +0000 2016',
  id: 716266356606443500,
  id_str: '716266356606443521',
  text: 'The weather in Krumbach, DE: Clear and 60.1 degrees on 04/02/2016',
  entities: { hashtags: [], symbols: [], user_mentions: [], urls: [] },
  truncated: false,
  source: '<a href="http://www.minneapolis.edu/" rel="nofollow">quotesBot</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user:
   { id: 709115368967635000,
     id_str: '709115368967634946',
     name: 'M Elkins',
     screen_name: 'mbeWorldWeather',
     location: '',
     description: '',
     url: null,
     entities: { description: [Object] },
     protected: false,
     followers_count: 0,
     friends_count: 0,
     listed_count: 0,
     created_at: 'Sun Mar 13 20:34:13 +0000 2016',
     favourites_count: 0,
     utc_offset: -25200,
     time_zone: 'Pacific Time (US & Canada)',
     geo_enabled: false,
     verified: false,
     statuses_count: 69,
     lang: 'en',
     contributors_enabled: false,
     is_translator: false,
     is_translation_enabled: false,
     profile_background_color: 'F5F8FA',
     profile_background_image_url: null,
     profile_background_image_url_https: null,
     profile_background_tile: false,
     profile_image_url: 'http://abs.twimg.com/sticky/default_profile_images/defa
ult_profile_2_normal.png',
     profile_image_url_https: 'https://abs.twimg.com/sticky/default_profile_imag
es/default_profile_2_normal.png',
     profile_link_color: '2B7BB9',
     profile_sidebar_border_color: 'C0DEED',
     profile_sidebar_fill_color: 'DDEEF6',
     profile_text_color: '333333',
     profile_use_background_image: true,
     has_extended_profile: false,
     default_profile: true,
     default_profile_image: true,
     following: false,
     follow_request_sent: false,
     notifications: false },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 0,
  favorite_count: 0,
  favorited: false,
  retweeted: false,
  lang: 'en' }