/*
idea for maps search param vals:
https://www.google.com/maps/place/Sakaka+Saudi+Arabia/@29.901596,39.8291775,10z/data=!3m1!4b1!4m2!3m1!1s0x1572b94c63eeeaf9:0x1f06043b3222855a

@data=!3m1!4b1!4m2!3m1!1s0x1572b94c63eeeaf9:0x1f06043b3222855a
*/

{  
   "city":{  
      "id":5037649,
      "name":"Minneapolis",
      "coord":{  
         "lon":-93.26384,
         "lat":44.979969
      },
      "country":"US",
      "population":0,
      "sys":{  
         "population":0
      }
   },
   "cod":"200",
   "message":0.0114,
   "cnt":40,
   "list":[  
      {  
         "dt":1459533600,
         "main":{  
            "temp":276.74,
            "temp_min":274.67,
            "temp_max":276.74,
            "pressure":991.46,
            "sea_level":1027.25,
            "grnd_level":991.46,
            "humidity":63,
            "temp_kf":2.07
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{  
            "all":24
         },
         "wind":{  
            "speed":7.92,
            "deg":324.51
         },
         "rain":{  

         },
         "snow":{  
            "3h":0.001
         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-04-01 18:00:00"
      },
      {  
         "dt":1459544400,
         "main":{  
            "temp":277.03,
            "temp_min":275.069,
            "temp_max":277.03,
            "pressure":991.49,
            "sea_level":1027.19,
            "grnd_level":991.49,
            "humidity":54,
            "temp_kf":1.96
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"02d"
            }
         ],
         "clouds":{  
            "all":8
         },
         "wind":{  
            "speed":7.5,
            "deg":313.006
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-04-01 21:00:00"
      },
      {  
         "dt":1459555200,
         "main":{  
            "temp":275.36,
            "temp_min":273.514,
            "temp_max":275.36,
            "pressure":990.99,
            "sea_level":1026.84,
            "grnd_level":990.99,
            "humidity":48,
            "temp_kf":1.85
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01n"
            }
         ],
         "clouds":{  
            "all":0
         },
         "wind":{  
            "speed":7.21,
            "deg":300.003
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-04-02 00:00:00"
      },
      {  
         "dt":1459566000,
         "main":{  
            "temp":273.49,
            "temp_min":271.752,
            "temp_max":273.49,
            "pressure":989.99,
            "sea_level":1025.99,
            "grnd_level":989.99,
            "humidity":57,
            "temp_kf":1.74
         },
         "weather":[  
            {  
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{  
            "all":48
         },
         "wind":{  
            "speed":4.66,
            "deg":282.004
         },
         "rain":{  
            "3h":0.0025
         },
         "snow":{  
            "3h":0.0135
         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-04-02 03:00:00"
      },
      {  
         "dt":1459576800,
         "main":{  
            "temp":274.13,
            "temp_min":272.498,
            "temp_max":274.13,
            "pressure":984.76,
            "sea_level":1020.81,
            "grnd_level":984.76,
            "humidity":70,
            "temp_kf":1.63
         },
         "weather":[  
            {  
               "id":600,
               "main":"Snow",
               "description":"light snow",
               "icon":"13n"
            }
         ],
         "clouds":{  
            "all":88
         },
         "wind":{  
            "speed":5.41,
            "deg":230.5
         },
         "rain":{  

         },
         "snow":{  
            "3h":0.34125
         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-04-02 06:00:00"
      },
      {  
         "dt":1459587600,
         "main":{  
            "temp":276.25,
            "temp_min":274.725,
            "temp_max":276.25,
            "pressure":982.92,
            "sea_level":1018.88,
            "grnd_level":982.92,
            "humidity":71,
            "temp_kf":1.52
         },
         "weather":[  
            {  
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{  
            "all":36
         },
         "wind":{  
            "speed":9.21,
            "deg":311.502
         },
         "rain":{  
            "3h":0.13
         },
         "snow":{  
            "3h":0.3075
         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-04-02 09:00:00"
      },
      {  
         "dt":1459598400,
         "main":{  
            "temp":271.51,
            "temp_min":270.094,
            "temp_max":271.51,
            "pressure":987.27,
            "sea_level":1023.7,
            "grnd_level":987.27,
            "humidity":58,
            "temp_kf":1.41
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{  
            "all":56
         },
         "wind":{  
            "speed":12.12,
            "deg":328.002
         },
         "rain":{  

         },
         "snow":{  
            "3h":0.00125
         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-04-02 12:00:00"
      },
      {  
         "dt":1459609200,
         "main":{  
            "temp":272.18,
            "temp_min":270.871,
            "temp_max":272.18,
            "pressure":991.92,
            "sea_level":1028.2,
            "grnd_level":991.92,
            "humidity":55,
            "temp_kf":1.31
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{  
            "all":44
         },
         "wind":{  
            "speed":9.72,
            "deg":331.001
         },
         "rain":{  

         },
         "snow":{  
            "3h":0.0025
         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-04-02 15:00:00"
      },
      {  
         "dt":1459620000,
         "main":{  
            "temp":274.26,
            "temp_min":273.065,
            "temp_max":274.26,
            "pressure":993.83,
            "sea_level":1029.87,
            "grnd_level":993.83,
            "humidity":47,
            "temp_kf":1.2
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{  
            "all":0
         },
         "wind":{  
            "speed":9.81,
            "deg":328.005
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-04-02 18:00:00"
      },
      {  
         "dt":1459630800,
         "main":{  
            "temp":276.12,
            "temp_min":275.029,
            "temp_max":276.12,
            "pressure":993.77,
            "sea_level":1029.51,
            "grnd_level":993.77,
            "humidity":48,
            "temp_kf":1.09
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{  
            "all":0
         },
         "wind":{  
            "speed":8.56,
            "deg":320
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-04-02 21:00:00"
      },
      {  
         "dt":1459641600,
         "main":{  
            "temp":275.82,
            "temp_min":274.836,
            "temp_max":275.82,
            "pressure":993.53,
            "sea_level":1029.25,
            "grnd_level":993.53,
            "humidity":51,
            "temp_kf":0.98
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01n"
            }
         ],
         "clouds":{  
            "all":0
         },
         "wind":{  
            "speed":6.36,
            "deg":309.004
         },
         "rain":{  

         },
         "snow":{  
            "3h":0.00125
         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-04-03 00:00:00"
      },
      {  
         "dt":1459652400,
         "main":{  
            "temp":273.24,
            "temp_min":272.371,
            "temp_max":273.24,
            "pressure":992.54,
            "sea_level":1028.76,
            "grnd_level":992.54,
            "humidity":72,
            "temp_kf":0.87
         },
         "weather":[  
            {  
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{  
            "all":68
         },
         "wind":{  
            "speed":1.31,
            "deg":301.504
         },
         "rain":{  
            "3h":0.01
         },
         "snow":{  
            "3h":0.03375
         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-04-03 03:00:00"
      },
      {  
         "dt":1459663200,
         "main":{  
            "temp":271.13,
            "temp_min":270.372,
            "temp_max":271.13,
            "pressure":989.97,
            "sea_level":1026.15,
            "grnd_level":989.97,
            "humidity":76,
            "temp_kf":0.76
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01n"
            }
         ],
         "clouds":{  
            "all":0
         },
         "wind":{  
            "speed":3.91,
            "deg":150.003
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-04-03 06:00:00"
      },
      {  
         "dt":1459674000,
         "main":{  
            "temp":272.22,
            "temp_min":271.568,
            "temp_max":272.22,
            "pressure":985.74,
            "sea_level":1021.8,
            "grnd_level":985.74,
            "humidity":84,
            "temp_kf":0.65
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01n"
            }
         ],
         "clouds":{  
            "all":0
         },
         "wind":{  
            "speed":3.76,
            "deg":172.002
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-04-03 09:00:00"
      },
      {  
         "dt":1459684800,
         "main":{  
            "temp":275.69,
            "temp_min":275.141,
            "temp_max":275.69,
            "pressure":982.07,
            "sea_level":1018.1,
            "grnd_level":982.07,
            "humidity":78,
            "temp_kf":0.54
         },
         "weather":[  
            {  
               "id":803,
               "main":"Clouds",
               "description":"broken clouds",
               "icon":"04d"
            }
         ],
         "clouds":{  
            "all":76
         },
         "wind":{  
            "speed":3.51,
            "deg":210.5
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-04-03 12:00:00"
      },
      {  
         "dt":1459695600,
         "main":{  
            "temp":283.8,
            "temp_min":283.367,
            "temp_max":283.8,
            "pressure":980.01,
            "sea_level":1015.3,
            "grnd_level":980.01,
            "humidity":64,
            "temp_kf":0.44
         },
         "weather":[  
            {  
               "id":803,
               "main":"Clouds",
               "description":"broken clouds",
               "icon":"04d"
            }
         ],
         "clouds":{  
            "all":76
         },
         "wind":{  
            "speed":3.87,
            "deg":233
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-04-03 15:00:00"
      },
      {  
         "dt":1459706400,
         "main":{  
            "temp":290.89,
            "temp_min":290.56,
            "temp_max":290.89,
            "pressure":978.82,
            "sea_level":1013.22,
            "grnd_level":978.82,
            "humidity":61,
            "temp_kf":0.33
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{  
            "all":0
         },
         "wind":{  
            "speed":5.16,
            "deg":269.002
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-04-03 18:00:00"
      },
      {  
         "dt":1459717200,
         "main":{  
            "temp":291.55,
            "temp_min":291.333,
            "temp_max":291.55,
            "pressure":979.11,
            "sea_level":1013.67,
            "grnd_level":979.11,
            "humidity":62,
            "temp_kf":0.22
         },
         "weather":[  
            {  
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{  
            "all":20
         },
         "wind":{  
            "speed":6.47,
            "deg":320.001
         },
         "rain":{  
            "3h":0.06
         },
         "snow":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-04-03 21:00:00"
      },
      {  
         "dt":1459728000,
         "main":{  
            "temp":284.34,
            "temp_min":284.227,
            "temp_max":284.34,
            "pressure":984.26,
            "sea_level":1019.23,
            "grnd_level":984.26,
            "humidity":61,
            "temp_kf":0.11
         },
         "weather":[  
            {  
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{  
            "all":32
         },
         "wind":{  
            "speed":7.36,
            "deg":356.003
         },
         "rain":{  
            "3h":0.04
         },
         "snow":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-04-04 00:00:00"
      },
      {  
         "dt":1459738800,
         "main":{  
            "temp":275.932,
            "temp_min":275.932,
            "temp_max":275.932,
            "pressure":990.8,
            "sea_level":1026.36,
            "grnd_level":990.8,
            "humidity":68,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01n"
            }
         ],
         "clouds":{  
            "all":0
         },
         "wind":{  
            "speed":6.76,
            "deg":7.50134
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-04-04 03:00:00"
      },
      {  
         "dt":1459749600,
         "main":{  
            "temp":271.84,
            "temp_min":271.84,
            "temp_max":271.84,
            "pressure":995.11,
            "sea_level":1031.11,
            "grnd_level":995.11,
            "humidity":69,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01n"
            }
         ],
         "clouds":{  
            "all":0
         },
         "wind":{  
            "speed":4.36,
            "deg":8.50247
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-04-04 06:00:00"
      },
      {  
         "dt":1459760400,
         "main":{  
            "temp":268.755,
            "temp_min":268.755,
            "temp_max":268.755,
            "pressure":997.47,
            "sea_level":1034,
            "grnd_level":997.47,
            "humidity":83,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01n"
            }
         ],
         "clouds":{  
            "all":0
         },
         "wind":{  
            "speed":2.11,
            "deg":357.001
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-04-04 09:00:00"
      },
      {  
         "dt":1459771200,
         "main":{  
            "temp":266.449,
            "temp_min":266.449,
            "temp_max":266.449,
            "pressure":999.87,
            "sea_level":1036.74,
            "grnd_level":999.87,
            "humidity":78,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{  
            "all":0
         },
         "wind":{  
            "speed":1.22,
            "deg":301
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-04-04 12:00:00"
      },
      {  
         "dt":1459782000,
         "main":{  
            "temp":274.342,
            "temp_min":274.342,
            "temp_max":274.342,
            "pressure":1002.39,
            "sea_level":1038.76,
            "grnd_level":1002.39,
            "humidity":75,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{  
            "all":0
         },
         "wind":{  
            "speed":1.96,
            "deg":300.503
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-04-04 15:00:00"
      },
      {  
         "dt":1459792800,
         "main":{  
            "temp":278.113,
            "temp_min":278.113,
            "temp_max":278.113,
            "pressure":1003.43,
            "sea_level":1039.34,
            "grnd_level":1003.43,
            "humidity":68,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{  
            "all":0
         },
         "wind":{  
            "speed":3.25,
            "deg":314.507
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-04-04 18:00:00"
      },
      {  
         "dt":1459803600,
         "main":{  
            "temp":280.675,
            "temp_min":280.675,
            "temp_max":280.675,
            "pressure":1002.9,
            "sea_level":1038.52,
            "grnd_level":1002.9,
            "humidity":62,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{  
            "all":0
         },
         "wind":{  
            "speed":3.41,
            "deg":312.504
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-04-04 21:00:00"
      },
      {  
         "dt":1459814400,
         "main":{  
            "temp":280.076,
            "temp_min":280.076,
            "temp_max":280.076,
            "pressure":1003.28,
            "sea_level":1038.99,
            "grnd_level":1003.28,
            "humidity":55,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":801,
               "main":"Clouds",
               "description":"few clouds",
               "icon":"02n"
            }
         ],
         "clouds":{  
            "all":24
         },
         "wind":{  
            "speed":2.47,
            "deg":330.012
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-04-05 00:00:00"
      },
      {  
         "dt":1459825200,
         "main":{  
            "temp":275.24,
            "temp_min":275.24,
            "temp_max":275.24,
            "pressure":1004.77,
            "sea_level":1041.14,
            "grnd_level":1004.77,
            "humidity":66,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":802,
               "main":"Clouds",
               "description":"scattered clouds",
               "icon":"03n"
            }
         ],
         "clouds":{  
            "all":44
         },
         "wind":{  
            "speed":2.47,
            "deg":39.5005
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-04-05 03:00:00"
      },
      {  
         "dt":1459836000,
         "main":{  
            "temp":273.138,
            "temp_min":273.138,
            "temp_max":273.138,
            "pressure":1005.49,
            "sea_level":1042.23,
            "grnd_level":1005.49,
            "humidity":63,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":801,
               "main":"Clouds",
               "description":"few clouds",
               "icon":"02n"
            }
         ],
         "clouds":{  
            "all":20
         },
         "wind":{  
            "speed":2.77,
            "deg":89.0007
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-04-05 06:00:00"
      },
      {  
         "dt":1459846800,
         "main":{  
            "temp":272.617,
            "temp_min":272.617,
            "temp_max":272.617,
            "pressure":1004.94,
            "sea_level":1041.79,
            "grnd_level":1004.94,
            "humidity":63,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":801,
               "main":"Clouds",
               "description":"few clouds",
               "icon":"02n"
            }
         ],
         "clouds":{  
            "all":20
         },
         "wind":{  
            "speed":3.91,
            "deg":113
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-04-05 09:00:00"
      },
      {  
         "dt":1459857600,
         "main":{  
            "temp":272.839,
            "temp_min":272.839,
            "temp_max":272.839,
            "pressure":1003.9,
            "sea_level":1040.73,
            "grnd_level":1003.9,
            "humidity":65,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":802,
               "main":"Clouds",
               "description":"scattered clouds",
               "icon":"03d"
            }
         ],
         "clouds":{  
            "all":44
         },
         "wind":{  
            "speed":4.67,
            "deg":135.006
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-04-05 12:00:00"
      },
      {  
         "dt":1459868400,
         "main":{  
            "temp":279.456,
            "temp_min":279.456,
            "temp_max":279.456,
            "pressure":1002.69,
            "sea_level":1038.69,
            "grnd_level":1002.69,
            "humidity":70,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":803,
               "main":"Clouds",
               "description":"broken clouds",
               "icon":"04d"
            }
         ],
         "clouds":{  
            "all":64
         },
         "wind":{  
            "speed":5.67,
            "deg":162.501
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-04-05 15:00:00"
      },
      {  
         "dt":1459879200,
         "main":{  
            "temp":282.15,
            "temp_min":282.15,
            "temp_max":282.15,
            "pressure":1000.14,
            "sea_level":1035.3,
            "grnd_level":1000.14,
            "humidity":71,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{  
            "all":76
         },
         "wind":{  
            "speed":8.76,
            "deg":173.5
         },
         "rain":{  
            "3h":0.15
         },
         "snow":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-04-05 18:00:00"
      },
      {  
         "dt":1459890000,
         "main":{  
            "temp":285.253,
            "temp_min":285.253,
            "temp_max":285.253,
            "pressure":995.39,
            "sea_level":1030.06,
            "grnd_level":995.39,
            "humidity":65,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{  
            "all":0
         },
         "wind":{  
            "speed":10.62,
            "deg":173
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-04-05 21:00:00"
      },
      {  
         "dt":1459900800,
         "main":{  
            "temp":284.902,
            "temp_min":284.902,
            "temp_max":284.902,
            "pressure":991.41,
            "sea_level":1026.05,
            "grnd_level":991.41,
            "humidity":64,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":802,
               "main":"Clouds",
               "description":"scattered clouds",
               "icon":"03n"
            }
         ],
         "clouds":{  
            "all":48
         },
         "wind":{  
            "speed":10.41,
            "deg":181.001
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-04-06 00:00:00"
      },
      {  
         "dt":1459911600,
         "main":{  
            "temp":284.385,
            "temp_min":284.385,
            "temp_max":284.385,
            "pressure":988.5,
            "sea_level":1023.17,
            "grnd_level":988.5,
            "humidity":60,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":803,
               "main":"Clouds",
               "description":"broken clouds",
               "icon":"04n"
            }
         ],
         "clouds":{  
            "all":64
         },
         "wind":{  
            "speed":9.76,
            "deg":181.001
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-04-06 03:00:00"
      },
      {  
         "dt":1459922400,
         "main":{  
            "temp":285.767,
            "temp_min":285.767,
            "temp_max":285.767,
            "pressure":983.79,
            "sea_level":1018.5,
            "grnd_level":983.79,
            "humidity":58,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":803,
               "main":"Clouds",
               "description":"broken clouds",
               "icon":"04n"
            }
         ],
         "clouds":{  
            "all":80
         },
         "wind":{  
            "speed":10.03,
            "deg":181.501
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-04-06 06:00:00"
      },
      {  
         "dt":1459933200,
         "main":{  
            "temp":288.383,
            "temp_min":288.383,
            "temp_max":288.383,
            "pressure":978.41,
            "sea_level":1013.17,
            "grnd_level":978.41,
            "humidity":54,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":803,
               "main":"Clouds",
               "description":"broken clouds",
               "icon":"04n"
            }
         ],
         "clouds":{  
            "all":68
         },
         "wind":{  
            "speed":11.28,
            "deg":191.003
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"n"
         },
         "dt_txt":"2016-04-06 09:00:00"
      },
      {  
         "dt":1459944000,
         "main":{  
            "temp":289.951,
            "temp_min":289.951,
            "temp_max":289.951,
            "pressure":976.29,
            "sea_level":1010.51,
            "grnd_level":976.29,
            "humidity":51,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":803,
               "main":"Clouds",
               "description":"broken clouds",
               "icon":"04d"
            }
         ],
         "clouds":{  
            "all":68
         },
         "wind":{  
            "speed":7.95,
            "deg":213.007
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-04-06 12:00:00"
      },
      {  
         "dt":1459954800,
         "main":{  
            "temp":289.127,
            "temp_min":289.127,
            "temp_max":289.127,
            "pressure":976.02,
            "sea_level":1010.28,
            "grnd_level":976.02,
            "humidity":67,
            "temp_kf":0
         },
         "weather":[  
            {  
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04d"
            }
         ],
         "clouds":{  
            "all":92
         },
         "wind":{  
            "speed":5.66,
            "deg":321.505
         },
         "rain":{  

         },
         "snow":{  

         },
         "sys":{  
            "pod":"d"
         },
         "dt_txt":"2016-04-06 15:00:00"
      }
   ]
}